version: '3.4'

services:
  microservicesdb:
    container_name: microservicesdb
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data:db
        #- ./data:/data/db
    ports:
        - "27017:27017" 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"

  microservices.products:
    container_name: microservicesproducts
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ProductDatabaseSettings:ConnectionString=mongodb://microservicesdb:27017"
    depends_on:
        - microservicesdb
    ports:
      - "8000:80"
    volumes:
      - ${HOME}/ASP.NET/Https:/root/.aspnet/https/
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
  microservices.sourcing:
    container_name: microservicessourcing
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "SourcingDatabaseSettings:ConnectionString=mongodb://microservicesdb:27017"
    depends_on:
      - microservicesdb
      - rabbitmq
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8001:80"

