version: '3.4'

services:
  microservicesdb:
    image: mongo
  
  rabbitmq:
    image: rabbitmq:3-management

  microservices.products:
    image: ${DOCKER_REGISTRY-}microservicesproducts
    build:
      context: .
      dockerfile: Microservices.Products/Dockerfile

  microservices.sourcing:
    image: ${DOCKER_REGISTRY-}microservicessourcing
    build:
      context: .
      dockerfile: Microservices.Sourcing/Dockerfile

